apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            component: web_client
    template:
        metadata:
            labels:
                component: web_client
        spec:
            containers:
                - name: client
                  image: kal17da/multicontainer-client
                  ports:
                      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: client-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: web_client
    ports:
        - port: 3000
          targetPort: 3000
