apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: "kal17da@gmail.com"
        privateKeySecretRef:
            name: letsencrypt-prod
        solvers:
            # https://cert-manager.io/docs/configuration/acme/http01/
            - http01:
                ingress:
                    class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: tonystark-tls
spec:
    secretName: tonystark-tls-secret
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
        group: cert-manager.io
    commonName: tonystark.dev
    dnsNames:
        - tonystark.dev
        - www.tonystark.dev


# You can run "kubectl get clusterissuers", "kubectl describe clusterissuers",
# "kubectl get certificates", and "kubectl describe certificates" to get more
# info on the status of certificate issuing
