apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: redis_cache
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
    template:
        metadata:
            labels:
                component: redis_cache
        spec:
            containers:
                - name: redis
                  image: redis
                  ports:
                      - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
    name: redis-cluster-ip-service
spec:
    type: ClusterIP
    selector:
        component: redis_cache
    ports:
        - port: 6379
          targetPort: 6379
